name: curso

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Etapa obrigatória "Checkout"
        uses: actions/checkout@v4

      - run: echo "Mensagem qualquer"

      - name: Instalação do Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Instala o miniconda
        uses: conda-incubator/setup-minconda@v3
        with:
          activate-environment: curso

      - name: Instala as bibliotecas python
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy yfinance