name: curso

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Etapa obrigatória "Checkout"
        uses: actions/checkout@v4

      - run: echo "Mensagem qualquer"

      - name: Instalação do Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Instala o Micromamba
        run: |
          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          chmod +x bin/micromamba
          ./bin/micromamba shell init -s bash -p ~/micromamba
          source ~/.bashrc
          micromamba create -n curso python=3.9 --yes
          micromamba activate curso

      - name: Instala as bibliotecas python
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy yfinance